import { describe, it, expect } from "vitest";
import { TemplateScriptSchema } from "./template-script-schema.js";

const base = {
  version: "1.0",
  renderer: "hyperframes",
  metadata: {
    title: "Test",
    source: { url: "", domain: "", image: null },
    channel: "VideAuto",
  },
  voice: { provider: "omnivoice", speed: 1.0 },
  aspect: "9:16",
  scenes: [
    { id: "hook", type: "hook", voiceText: "x", templateId: "frame-glass-hero", inputs: {} },
    { id: "body-1", type: "body", voiceText: "x", templateId: "frame-visual-body", inputs: {} },
    { id: "outro", type: "outro", voiceText: "x", templateId: "frame-image-outro", inputs: {} },
  ],
};

describe("TemplateScriptSchema", () => {
  // Regression: `theme` was documented and generated by the AI but never declared
  // on the root schema, so Zod silently stripped it and every template fell back
  // to its hard-coded colors.
  it("keeps the theme object after parsing", () => {
    const parsed = TemplateScriptSchema.parse({
      ...base,
      theme: { bgPrimary: "#020c1a", accent1: "#ff4d6d", mood: "dark" },
    });
    expect(parsed.theme).toEqual({ bgPrimary: "#020c1a", accent1: "#ff4d6d", mood: "dark" });
  });

  it("accepts a partial theme and defaults mood to dark", () => {
    const parsed = TemplateScriptSchema.parse({ ...base, theme: { accent1: "#fff" } });
    expect(parsed.theme?.mood).toBe("dark");
  });

  it("leaves theme undefined when the script omits it", () => {
    expect(TemplateScriptSchema.parse(base).theme).toBeUndefined();
  });

  it("rejects a script whose first scene is not a hook", () => {
    const bad = { ...base, scenes: [{ ...base.scenes[1] }, ...base.scenes.slice(1)] };
    expect(() => TemplateScriptSchema.parse(bad)).toThrow();
  });
});
